### PR TITLE
created jetpack compose recycleview

### PR DESCRIPTION
**Pull request by coffmancorrim**
I wrote some code.

### CODE REVIEW

**Review by muzzarellimj — APPROVED** [review]

**Review by arthurwb — APPROVED** [review]
Looks Good!

**Comment by huzaifa-f** [comment]
approved

**Review by arthurwb — APPROVED** [review]
Looks even better the second time.

**Review by huzaifa-f — COMMENTED** [review]
approved

**Review by huzaifa-f — APPROVED** [review]

**Pull request merged**
